import type { Product } from "@/types"

export const categories = [
  { id: "cotton", name: "Cotton", image: "images/si.jpg?height=200&width=300" },
  { id: "silk", name: "Silk", image: "images/silk.jpg?height=200&width=300" },
  { id: "linen", name: "Linen", image: "images/len.jpg?height=200&width=300" },
  { id: "wool", name: "Wool", image: "images/wool.jpg?height=200&width=300" },
]

export const products: Product[] = [
  {
    id: "1",
    name: "Premium Cotton Fabric",
    description:
      "High-quality 100% organic cotton fabric perfect for clothing and home textiles. Soft, breathable, and durable.",
    price: 24.99,
    originalPrice: 29.99,
    category: "cotton",
    images: [
      "/images/si.jpg?height=400&width=400",
      "/images/su.jpg?height=400&width=400",
      "/images/sq.jpg?height=400&width=400",
    ],
    inStock: true,
    material: "Cotton",
    colors: ["White", "Beige", "Light Blue"],
    sizes: ["1 yard", "2 yards", "5 yards"],
    featured: true,
  },
  {
    id: "2",
    name: "Luxury Silk Fabric",
    description: "Elegant mulberry silk fabric with a lustrous finish. Perfect for formal wear and luxury home decor.",
    price: 89.99,
    category: "silk",
    images: ["/images/sx.jpg?height=400&width=400", "/images/ss.jpg?height=400&width=400"],
    inStock: true,
    material: "Silk",
    colors: ["Ivory", "Champagne", "Deep Red"],
    sizes: ["1 yard", "2 yards", "3 yards"],
    featured: true,
  },
  {
    id: "3",
    name: "Natural Linen Fabric",
    description: "Breathable and lightweight linen fabric ideal for summer clothing and casual wear.",
    price: 34.99,
    category: "linen",
    images: ["/images/sc.jpg?height=400&width=400", "/images/cc.jpg?height=400&width=400"],
    inStock: true,
    material: "Linen",
    colors: ["Natural", "White", "Stone Gray"],
    sizes: ["1 yard", "2 yards", "4 yards"],
    featured: true,
  },
  {
    id: "4",
    name: "Merino Wool Fabric",
    description: "Soft and warm merino wool fabric perfect for winter clothing and accessories.",
    price: 54.99,
    category: "wool",
    images: ["/images/sd.jpg?height=400&width=400"],
    inStock: true,
    material: "Wool",
    colors: ["Charcoal", "Navy", "Burgundy"],
    sizes: ["1 yard", "2 yards", "3 yards"],
  },
  {
    id: "5",
    name: "Organic Cotton Blend",
    description: "Sustainable cotton blend fabric with excellent drape and comfort.",
    price: 19.99,
    originalPrice: 24.99,
    category: "cotton",
    images: ["/images/so.jpg?height=400&width=400"],
    inStock: true,
    material: "Cotton Blend",
    colors: ["Cream", "Sage Green", "Dusty Pink"],
    sizes: ["1 yard", "2 yards", "5 yards"],
  },
  {
    id: "6",
    name: "Printed Silk Scarf Fabric",
    description: "Beautiful printed silk fabric perfect for scarves and accessories.",
    price: 64.99,
    category: "silk",
    images: ["/images/sf.jpg?height=400&width=400"],
    inStock: false,
    material: "Silk",
    colors: ["Floral Print", "Geometric Print"],
    sizes: ["1 yard", "2 yards"],
  },
]
